src/Yom.Web/Models/ReferenceUser/ReferenceUserCreateModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using DataAnnotationsExtensions;

namespace Yom.Web.Models.ReferenceUser
{
    public class ReferenceUserCreateModel
    {
        public string LastName { get; set; }
        public string FirstName { get; set; }

        [Required]
        [Email]
        [DataType(DataType.EmailAddress)]
        public string Mail { get; set; }

    }
}

src/Yom.Web/Models/ReferenceUser/ReferenceUserViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace Yom.Web.Models.ReferenceUser
{
    public class ReferenceUserViewModel
    {
        public ReferenceUserViewModel(Yom.Lib.Data.EF.ReferenceUser model)
        {
            Id = model.Id;
            Mail = model.Mail;
            Firstname = model.Firstname;
            Lastname = model.Lastname;
        }

        public long Id { get; private set; }
        public string Mail { get; private set; }
        public string Firstname { get; private set; }
        public string Lastname { get; private set; }

        public override string ToString()
        {
            return string.Format("{0} {1} <{2}>",Firstname,Lastname,Mail);
        }
    }
}

src/Yom.Web/Controllers/ReferenceUserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Yom.Web.Models.ReferenceUser;
using Yom.Lib.Services;
using Yom.Web.Helper;

namespace Yom.Web.Controllers
{
    [RedirectToPrevious]
    public class ReferenceUserController : Controller
    {
        private IReferenceUserService ReferenceUserService;

        public ReferenceUserController(IReferenceUserService referenceUserService)
        {
            ReferenceUserService = referenceUserService;
        }

        //
        // GET: /ReferenceUser/

        public ActionResult Index()
        {
            var model = from i in ReferenceUserService.Get()
                        select new ReferenceUserViewModel(i);

            return View(model);
        }

        //
        // GET: /ReferenceUser/Details/5

        //public ActionResult Details(long id)
        //{
        //    return View();
        //}

        //
        // GET: /ReferenceUser/Create

        public ActionResult Create()
        {
            

            return View();
        }

        //
        // POST: /ReferenceUser/Create

        [HttpPost]
        public ActionResult Create(ReferenceUserCreateModel model)
        {
            if (ModelState.IsValid)
            {
                var retVal = ReferenceUserService.Create(model.Mail, model.LastName, model.FirstName);

                if (retVal.IsSuccessful)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    ModelState.AddModelError("", retVal.Message);
                }
            }

            

            return View();
        }

        //
        // GET: /ReferenceUser/Edit/5

        //public ActionResult Edit(int id)
        //{
        //    return View();
        //}

        ////
        //// POST: /ReferenceUser/Edit/5

        //[HttpPost]
        //public ActionResult Edit(int id, FormCollection collection)
        //{
        //    try
        //    {
        //        // TODO: Add update logic here

        //        return RedirectToAction("Index");
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}

        ////
        //// GET: /ReferenceUser/Delete/5

        //public ActionResult Delete(int id)
        //{
        //    return View();
        //}

        ////
        //// POST: /ReferenceUser/Delete/5

        //[HttpPost]
        //public ActionResult Delete(int id, FormCollection collection)
        //{
        //    try
        //    {
        //        // TODO: Add delete logic here

        //        return RedirectToAction("Index");
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}
    }
}

src/Yom.Web/Views/ReferenceUser/Create.cshtml
@model Yom.Web.Models.ReferenceUser.ReferenceUserCreateModel
@{
    ViewBag.Title = "Create";
}

@using (Html.BeginForm(null, null, FormMethod.Post)) 
{
    @Html.ValidationSummary(false)
    <div data-role="fieldcontain">
        @Html.LabelFor(model => model.FirstName)
        @Html.EditorFor(model => model.FirstName)
        @*@Html.ValidationMessageFor(model => model.FirstName, "*")*@
    </div>
    
    <div data-role="fieldcontain">
        @Html.LabelFor(model => model.LastName)
        @Html.EditorFor(model => model.LastName)
        @*@Html.ValidationMessageFor(model => model.LastName, "*")*@
    </div>

    <div data-role="fieldcontain">
        @Html.LabelFor(model => model.Mail)
        @Html.EditorFor(model => model.Mail)
        @*@Html.ValidationMessageFor(model => model.Mail, "*")*@
    </div>

    <p>
        <input type="submit" value="Create" />
    </p>
}

src/Yom.Web/Views/ReferenceUser/Index.cshtml
@model IEnumerable<Yom.Web.Models.ReferenceUser.ReferenceUserViewModel>
@{
    ViewBag.Title = "Index";
    ViewBag.DataUrl = "/ReferenceUser/Index";
}
<div class="append-bottom">
    @Html.ActionLink("Create Reference User", "Create", null, new { data_role = "button" })
</div>
<ul data-role="listview" >
    @foreach (var item in Model)
    { 
        <li>@Html.ActionLink(item.ToString(), "Details", "ReferenceUser", new { id = item.Id }, null)</li>
    }
</ul>